RevisionTypeResolver using drools is replaced with custom code. Drools is not used anymore!
Problem with drools:
Drools is NOT able to locate the rule spreadsheet file from within the jar. But drools DOES locate the rule spreadsheet file when running the unit tests.
Exception is:
java.lang.StringIndexOutOfBoundsException: Range [5, 3) out of bounds for length 164
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4950)
at java.base/java.lang.String.substring(String.java:2912)
at org.drools.ruleunits.impl.RuleUnitProviderImpl.collectResourcesInJar(RuleUnitProviderImpl.java:192)
at org.drools.ruleunits.impl.RuleUnitProviderImpl.ruleResourcesForUnitClass(RuleUnitProviderImpl.java:140)